### ISSUE TITLE
"header", "parameter" or "header parameter"

### ISSUE THREAD

**Issue by laurencelundblade** [cose-wg/cose-rfc8152bis#17]
Is a kid, iv, content type... a "header", a "parameter" or a "header parameter"?

The textual description of each refers to them as "parameters" -- "This parameter is used to indicate..."

The summarizing table 2 calls them "header parameters". 

The paragraph on CDDL and the CDDL refers them as "headers".

I was theorizing that protected and unprotected are headers and kid, iv... are parameters or header parameters, but that isn't consistent with the text.

No ambiguity when implementing, but a little confusing to read.

If the official name is "header parameter" and "parameter" is the short name, then the main divergence is the CDDL and CDDL-related text. If the CDDL and CDDL-related text where changed to  use "header parameter" it seems like all would be consistent.

**Comment by jimsch** [comment]
Done - and I don't see why it is marked open
