### ISSUE TITLE
Use CDDL <<>> notation in examples

### ISSUE THREAD

**Issue by ciphergoth** [cose-wg/cose-rfc8152bis#27]
When COSE was first designed CDDL was still incomplete, and so the COSE RFC expresses the content of binary blobs that contain CDDL using a comment - with "comments" that live inside the comment set off by backslashes [eg](https://github.com/cose-wg/cose-rfc8152bis/blob/08ac00ae1a3a0722fc2ff894455967bf04df8683/draft-ietf-cose-rfc8152bis-struct.xml#L2227):

    / protected / h'a10101' / {
        \ alg \ 1:1 \ AES-GCM 128 \
      } / , 

CDDL's Extended Diagnostic Notation now defines a clean way to handle this situation, using double angle brackets; the above can now be expressed as:

    / protected / << {
        / alg / 1:1 / AES-GCM 128 /
    } >> ,

which is easier to read and communicates the intent more clearly.

**Comment by jimsch** [comment]
My first issue is that in this case I think that the encoded bytes is something that needs to be part of the example.  This is because the actual encoded byte string has security properties.  I will think about this.

**Comment by ciphergoth** [comment]
Would it make sense to use the Extended Diagnostic Notation, but put the actual bytes in a comment?

**Comment by jimsch** [comment]
Done
